name: Deploy prod to AWS
on:
  push:
    branches:
      - master

# concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency: merge-${{ github.ref }}

# permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  DeployApp:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.SITE_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: configure credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: eu-west-1

      - name: installing dependencies
        run: |
          npx update-browserslist-db@latest
          npm ci

      - name: Deploy app
        id: deploy
        run: |
          deploy_output=$(npm run deploy -- --stage prod --verbose || true)
          echo "$deploy_output"
          site_url=$(echo "$deploy_output" | grep "SiteUrl:" | awk '{print $2}')
          echo "site_url is now set to: $site_url"
          echo SITE_URL=$site_url >> $GITHUB_OUTPUT
